class AdImageLinksSet < ::ApplicationRecord
  extend _ActiveRecord_Relation_ClassMethods[AdImageLinksSet, ActiveRecord_Relation, Integer]

  module GeneratedAttributeMethods
    def ad_id: () -> Integer

    def ad_id=: (Integer) -> Integer

    def ad_id?: () -> bool

    def ad_id_changed?: () -> bool

    def ad_id_change: () -> [ Integer?, Integer? ]

    def ad_id_will_change!: () -> void

    def ad_id_was: () -> Integer?

    def ad_id_previously_changed?: () -> bool

    def ad_id_previous_change: () -> Array[Integer?]?

    def ad_id_previously_was: () -> Integer?

    def ad_id_before_last_save: () -> Integer?

    def ad_id_change_to_be_saved: () -> Array[Integer?]?

    def ad_id_in_database: () -> Integer?

    def saved_change_to_ad_id: () -> Array[Integer?]?

    def saved_change_to_ad_id?: () -> bool

    def will_save_change_to_ad_id?: () -> bool

    def restore_ad_id!: () -> void

    def clear_ad_id_change: () -> void

    def value: () -> String?

    def value=: (String?) -> String?

    def value?: () -> bool

    def value_changed?: () -> bool

    def value_change: () -> [ String?, String? ]

    def value_will_change!: () -> void

    def value_was: () -> String?

    def value_previously_changed?: () -> bool

    def value_previous_change: () -> Array[String?]?

    def value_previously_was: () -> String?

    def value_before_last_save: () -> String?

    def value_change_to_be_saved: () -> Array[String?]?

    def value_in_database: () -> String?

    def saved_change_to_value: () -> Array[String?]?

    def saved_change_to_value?: () -> bool

    def will_save_change_to_value?: () -> bool

    def restore_value!: () -> void

    def clear_value_change: () -> void
  end
  include GeneratedAttributeMethods

  def ad: () -> Ad
  def ad=: (Ad?) -> Ad?
  def reload_ad: () -> Ad?
  def build_ad: (untyped) -> Ad
  def create_ad: (untyped) -> Ad
  def create_ad!: (untyped) -> Ad

  module GeneratedRelationMethods
  end

  class ActiveRecord_Relation < ::ActiveRecord::Relation
    include GeneratedRelationMethods
    include _ActiveRecord_Relation[AdImageLinksSet, Integer]
    include Enumerable[AdImageLinksSet]
  end

  class ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include GeneratedRelationMethods
    include _ActiveRecord_Relation[AdImageLinksSet, Integer]
  end
end
