class City < ::ApplicationRecord
  extend _ActiveRecord_Relation_ClassMethods[City, ActiveRecord_Relation, Integer]

  module GeneratedAttributeMethods
    def id: () -> Integer

    def id=: (Integer) -> Integer

    def id?: () -> bool

    def id_changed?: () -> bool

    def id_change: () -> [ Integer?, Integer? ]

    def id_will_change!: () -> void

    def id_was: () -> Integer?

    def id_previously_changed?: () -> bool

    def id_previous_change: () -> Array[Integer?]?

    def id_previously_was: () -> Integer?

    def id_before_last_save: () -> Integer?

    def id_change_to_be_saved: () -> Array[Integer?]?

    def id_in_database: () -> Integer?

    def saved_change_to_id: () -> Array[Integer?]?

    def saved_change_to_id?: () -> bool

    def will_save_change_to_id?: () -> bool

    def restore_id!: () -> void

    def clear_id_change: () -> void

    def name: () -> String

    def name=: (String) -> String

    def name?: () -> bool

    def name_changed?: () -> bool

    def name_change: () -> [ String?, String? ]

    def name_will_change!: () -> void

    def name_was: () -> String?

    def name_previously_changed?: () -> bool

    def name_previous_change: () -> Array[String?]?

    def name_previously_was: () -> String?

    def name_before_last_save: () -> String?

    def name_change_to_be_saved: () -> Array[String?]?

    def name_in_database: () -> String?

    def saved_change_to_name: () -> Array[String?]?

    def saved_change_to_name?: () -> bool

    def will_save_change_to_name?: () -> bool

    def restore_name!: () -> void

    def clear_name_change: () -> void

    def region_id: () -> Integer

    def region_id=: (Integer) -> Integer

    def region_id?: () -> bool

    def region_id_changed?: () -> bool

    def region_id_change: () -> [ Integer?, Integer? ]

    def region_id_will_change!: () -> void

    def region_id_was: () -> Integer?

    def region_id_previously_changed?: () -> bool

    def region_id_previous_change: () -> Array[Integer?]?

    def region_id_previously_was: () -> Integer?

    def region_id_before_last_save: () -> Integer?

    def region_id_change_to_be_saved: () -> Array[Integer?]?

    def region_id_in_database: () -> Integer?

    def saved_change_to_region_id: () -> Array[Integer?]?

    def saved_change_to_region_id?: () -> bool

    def will_save_change_to_region_id?: () -> bool

    def restore_region_id!: () -> void

    def clear_region_id_change: () -> void

    def translations: () -> untyped?

    def translations=: (untyped?) -> untyped?

    def translations?: () -> bool

    def translations_changed?: () -> bool

    def translations_change: () -> [ untyped?, untyped? ]

    def translations_will_change!: () -> void

    def translations_was: () -> untyped?

    def translations_previously_changed?: () -> bool

    def translations_previous_change: () -> Array[untyped?]?

    def translations_previously_was: () -> untyped?

    def translations_before_last_save: () -> untyped?

    def translations_change_to_be_saved: () -> Array[untyped?]?

    def translations_in_database: () -> untyped?

    def saved_change_to_translations: () -> Array[untyped?]?

    def saved_change_to_translations?: () -> bool

    def will_save_change_to_translations?: () -> bool

    def restore_translations!: () -> void

    def clear_translations_change: () -> void
  end
  include GeneratedAttributeMethods

  def region: () -> Region
  def region=: (Region?) -> Region?
  def reload_region: () -> Region?
  def build_region: (untyped) -> Region
  def create_region: (untyped) -> Region
  def create_region!: (untyped) -> Region

  module GeneratedRelationMethods
  end

  class ActiveRecord_Relation < ::ActiveRecord::Relation
    include GeneratedRelationMethods
    include _ActiveRecord_Relation[City, Integer]
    include Enumerable[City]
  end

  class ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include GeneratedRelationMethods
    include _ActiveRecord_Relation[City, Integer]
  end
end
