#!/bin/sh

if [ $(git branch --show-current) == "master" ]; then
  ./bin/rubocop

  (($? != 0)) && { printf '%s\n' "Please fox Rubocop"; exit 1; }

  ./bin/rspec --fail-fast

  (($? != 0)) && { printf '%s\n' "Please fix specs"; exit 1; }
fi

exit 0
