require:
  - rubocop-performance
  - rubocop-rspec

inherit_gem:
  rubocop-shopify: rubocop.yml

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  DisplayStyleGuide: true
  SuggestExtensions: false
  Exclude:
    - 'vendor/bundle/**/*'
    - 'db/migrate/**/*'

Layout/LineLength:
  Enabled: false
