interface _RbsRailsPathHelpers
  def rails_info_properties_path: (*untyped) -> String
  def rails_info_routes_path: (*untyped) -> String
  def rails_info_path: (*untyped) -> String
  def ios_path: (*untyped) -> String
  def apk_path: (*untyped) -> String
  def android_path: (*untyped) -> String
  def news_path: (*untyped) -> String
  def chat_path: (*untyped) -> String
  def whitepaper_path: (*untyped) -> String
  def new_admin_user_session_path: (*untyped) -> String
  def admin_user_session_path: (*untyped) -> String
  def destroy_admin_user_session_path: (*untyped) -> String
  def admin_root_path: (*untyped) -> String
  def reorder_admin_ad_option_types_path: (*untyped) -> String
  def admin_ad_option_types_path: (*untyped) -> String
  def new_admin_ad_option_type_path: (*untyped) -> String
  def edit_admin_ad_option_type_path: (*untyped) -> String
  def admin_ad_option_type_path: (*untyped) -> String
  def batch_action_admin_categories_path: (*untyped) -> String
  def admin_categories_path: (*untyped) -> String
  def new_admin_category_path: (*untyped) -> String
  def edit_admin_category_path: (*untyped) -> String
  def admin_category_path: (*untyped) -> String
  def batch_action_admin_cities_path: (*untyped) -> String
  def admin_cities_path: (*untyped) -> String
  def new_admin_city_path: (*untyped) -> String
  def edit_admin_city_path: (*untyped) -> String
  def admin_city_path: (*untyped) -> String
  def admin_dashboard_path: (*untyped) -> String
  def batch_action_admin_demo_phone_numbers_path: (*untyped) -> String
  def admin_demo_phone_numbers_path: (*untyped) -> String
  def new_admin_demo_phone_number_path: (*untyped) -> String
  def edit_admin_demo_phone_number_path: (*untyped) -> String
  def admin_demo_phone_number_path: (*untyped) -> String
  def batch_action_admin_filterable_values_path: (*untyped) -> String
  def admin_filterable_values_path: (*untyped) -> String
  def new_admin_filterable_value_path: (*untyped) -> String
  def edit_admin_filterable_value_path: (*untyped) -> String
  def admin_filterable_value_path: (*untyped) -> String
  def reorder_admin_filterable_values_groups_path: (*untyped) -> String
  def admin_filterable_values_groups_path: (*untyped) -> String
  def new_admin_filterable_values_group_path: (*untyped) -> String
  def edit_admin_filterable_values_group_path: (*untyped) -> String
  def admin_filterable_values_group_path: (*untyped) -> String
  def batch_action_admin_phone_numbers_path: (*untyped) -> String
  def admin_phone_numbers_path: (*untyped) -> String
  def batch_action_admin_regions_path: (*untyped) -> String
  def admin_regions_path: (*untyped) -> String
  def new_admin_region_path: (*untyped) -> String
  def edit_admin_region_path: (*untyped) -> String
  def admin_region_path: (*untyped) -> String
  def admin_ad_option_type_sortable_path: (*untyped) -> String
  def batch_action_admin_users_path: (*untyped) -> String
  def admin_users_path: (*untyped) -> String
  def admin_user_path: (*untyped) -> String
  def admin_comments_path: (*untyped) -> String
  def admin_comment_path: (*untyped) -> String
  def sidekiq_web_path: (*untyped) -> String
  def health_path: (*untyped) -> String
  def tos_path: (*untyped) -> String
  def privacy_path: (*untyped) -> String
  def show_budget_ads_path: (*untyped) -> String
  def show_model_path: (*untyped) -> String
  def show_model_year_path: (*untyped) -> String
  def search_models_path: (*untyped) -> String
  def ad_path: (*untyped) -> String
  def api_filters_path: (*untyped) -> String
  def api_v1_settings_path: (*untyped) -> String
  def api_v1_contact_book_path: (*untyped) -> String
  def set_referrer_api_v1_user_path: (*untyped) -> String
  def api_v1_user_path: (*untyped) -> String
  def api_v1_sessions_path: (*untyped) -> String
  def api_v1_ad_path: (*untyped) -> String
  def api_v1_friendly_ad_path: (*untyped) -> String
  def api_v1_user_contacts_path: (*untyped) -> String
  def api_v1_favorite_ads_path: (*untyped) -> String
  def api_v1_favorite_ad_path: (*untyped) -> String
  def api_v1_visited_ads_path: (*untyped) -> String
  def api_v1_my_ads_path: (*untyped) -> String
  def api_v1_feed_ads_path: (*untyped) -> String
  def api_v1_chat_rooms_path: (*untyped) -> String
  def api_v1_chat_room_users_path: (*untyped) -> String
  def api_v1_chat_room_user_path: (*untyped) -> String
  def api_v1_messages_path: (*untyped) -> String
  def api_v1_admin_system_messages_path: (*untyped) -> String
  def api_v1_referrer_path: (*untyped) -> String
  def api_v1_blocked_user_contact_path: (*untyped) -> String
  def api_v1_admin_system_chat_rooms_path: (*untyped) -> String
  def api_v1_admin_system_chat_room_path: (*untyped) -> String
  def api_v1_system_chat_room_path: (*untyped) -> String
  def api_v1_presigner_path: (*untyped) -> String
  def api_v2_friendly_ad_path: (*untyped) -> String
  def api_v2_feed_ads_path: (*untyped) -> String
  def api_v2_ads_path: (*untyped) -> String
  def api_v2_ad_path: (*untyped) -> String
  def api_v2_my_ads_path: (*untyped) -> String
  def api_v2_favorite_ads_path: (*untyped) -> String
  def api_v2_visited_ads_path: (*untyped) -> String
  def rails_info_properties_url: (*untyped) -> String
  def rails_info_routes_url: (*untyped) -> String
  def rails_info_url: (*untyped) -> String
  def ios_url: (*untyped) -> String
  def apk_url: (*untyped) -> String
  def android_url: (*untyped) -> String
  def news_url: (*untyped) -> String
  def chat_url: (*untyped) -> String
  def whitepaper_url: (*untyped) -> String
  def new_admin_user_session_url: (*untyped) -> String
  def admin_user_session_url: (*untyped) -> String
  def destroy_admin_user_session_url: (*untyped) -> String
  def admin_root_url: (*untyped) -> String
  def reorder_admin_ad_option_types_url: (*untyped) -> String
  def admin_ad_option_types_url: (*untyped) -> String
  def new_admin_ad_option_type_url: (*untyped) -> String
  def edit_admin_ad_option_type_url: (*untyped) -> String
  def admin_ad_option_type_url: (*untyped) -> String
  def batch_action_admin_categories_url: (*untyped) -> String
  def admin_categories_url: (*untyped) -> String
  def new_admin_category_url: (*untyped) -> String
  def edit_admin_category_url: (*untyped) -> String
  def admin_category_url: (*untyped) -> String
  def batch_action_admin_cities_url: (*untyped) -> String
  def admin_cities_url: (*untyped) -> String
  def new_admin_city_url: (*untyped) -> String
  def edit_admin_city_url: (*untyped) -> String
  def admin_city_url: (*untyped) -> String
  def admin_dashboard_url: (*untyped) -> String
  def batch_action_admin_demo_phone_numbers_url: (*untyped) -> String
  def admin_demo_phone_numbers_url: (*untyped) -> String
  def new_admin_demo_phone_number_url: (*untyped) -> String
  def edit_admin_demo_phone_number_url: (*untyped) -> String
  def admin_demo_phone_number_url: (*untyped) -> String
  def batch_action_admin_filterable_values_url: (*untyped) -> String
  def admin_filterable_values_url: (*untyped) -> String
  def new_admin_filterable_value_url: (*untyped) -> String
  def edit_admin_filterable_value_url: (*untyped) -> String
  def admin_filterable_value_url: (*untyped) -> String
  def reorder_admin_filterable_values_groups_url: (*untyped) -> String
  def admin_filterable_values_groups_url: (*untyped) -> String
  def new_admin_filterable_values_group_url: (*untyped) -> String
  def edit_admin_filterable_values_group_url: (*untyped) -> String
  def admin_filterable_values_group_url: (*untyped) -> String
  def batch_action_admin_phone_numbers_url: (*untyped) -> String
  def admin_phone_numbers_url: (*untyped) -> String
  def batch_action_admin_regions_url: (*untyped) -> String
  def admin_regions_url: (*untyped) -> String
  def new_admin_region_url: (*untyped) -> String
  def edit_admin_region_url: (*untyped) -> String
  def admin_region_url: (*untyped) -> String
  def admin_ad_option_type_sortable_url: (*untyped) -> String
  def batch_action_admin_users_url: (*untyped) -> String
  def admin_users_url: (*untyped) -> String
  def admin_user_url: (*untyped) -> String
  def admin_comments_url: (*untyped) -> String
  def admin_comment_url: (*untyped) -> String
  def sidekiq_web_url: (*untyped) -> String
  def health_url: (*untyped) -> String
  def tos_url: (*untyped) -> String
  def privacy_url: (*untyped) -> String
  def show_budget_ads_url: (*untyped) -> String
  def show_model_url: (*untyped) -> String
  def show_model_year_url: (*untyped) -> String
  def search_models_url: (*untyped) -> String
  def ad_url: (*untyped) -> String
  def api_filters_url: (*untyped) -> String
  def api_v1_settings_url: (*untyped) -> String
  def api_v1_contact_book_url: (*untyped) -> String
  def set_referrer_api_v1_user_url: (*untyped) -> String
  def api_v1_user_url: (*untyped) -> String
  def api_v1_sessions_url: (*untyped) -> String
  def api_v1_ad_url: (*untyped) -> String
  def api_v1_friendly_ad_url: (*untyped) -> String
  def api_v1_user_contacts_url: (*untyped) -> String
  def api_v1_favorite_ads_url: (*untyped) -> String
  def api_v1_favorite_ad_url: (*untyped) -> String
  def api_v1_visited_ads_url: (*untyped) -> String
  def api_v1_my_ads_url: (*untyped) -> String
  def api_v1_feed_ads_url: (*untyped) -> String
  def api_v1_chat_rooms_url: (*untyped) -> String
  def api_v1_chat_room_users_url: (*untyped) -> String
  def api_v1_chat_room_user_url: (*untyped) -> String
  def api_v1_messages_url: (*untyped) -> String
  def api_v1_admin_system_messages_url: (*untyped) -> String
  def api_v1_referrer_url: (*untyped) -> String
  def api_v1_blocked_user_contact_url: (*untyped) -> String
  def api_v1_admin_system_chat_rooms_url: (*untyped) -> String
  def api_v1_admin_system_chat_room_url: (*untyped) -> String
  def api_v1_system_chat_room_url: (*untyped) -> String
  def api_v1_presigner_url: (*untyped) -> String
  def api_v2_friendly_ad_url: (*untyped) -> String
  def api_v2_feed_ads_url: (*untyped) -> String
  def api_v2_ads_url: (*untyped) -> String
  def api_v2_ad_url: (*untyped) -> String
  def api_v2_my_ads_url: (*untyped) -> String
  def api_v2_favorite_ads_url: (*untyped) -> String
  def api_v2_visited_ads_url: (*untyped) -> String
end
