development:
  adapter: redis
  url: <%= "redis://#{ENV['REDIS_SERVICE_HOST']}:6379" %>

test:
  adapter: test
  url: <%= "redis://#{ENV['REDIS_SERVICE_HOST']}:6379" %>

production:
  adapter: redis
  password: <%= "#{ENV['REDIS_SERVICE_PASSWORD']}" %>
  host: <%= "#{ENV['REDIS_SERVICE_HOST']}" %>
  port: <%= "#{ENV['REDIS_SERVICE_PORT']}" %>
