module ActiveAdmin
  class Comment < ::ActiveRecord::Base
    extend _ActiveRecord_Relation_ClassMethods[ActiveAdmin::Comment, ActiveRecord_Relation, Integer]

    module GeneratedAttributeMethods
      def id: () -> Integer

      def id=: (Integer) -> Integer

      def id?: () -> bool

      def id_changed?: () -> bool

      def id_change: () -> [ Integer?, Integer? ]

      def id_will_change!: () -> void

      def id_was: () -> Integer?

      def id_previously_changed?: () -> bool

      def id_previous_change: () -> Array[Integer?]?

      def id_previously_was: () -> Integer?

      def id_before_last_save: () -> Integer?

      def id_change_to_be_saved: () -> Array[Integer?]?

      def id_in_database: () -> Integer?

      def saved_change_to_id: () -> Array[Integer?]?

      def saved_change_to_id?: () -> bool

      def will_save_change_to_id?: () -> bool

      def restore_id!: () -> void

      def clear_id_change: () -> void

      def namespace: () -> String?

      def namespace=: (String?) -> String?

      def namespace?: () -> bool

      def namespace_changed?: () -> bool

      def namespace_change: () -> [ String?, String? ]

      def namespace_will_change!: () -> void

      def namespace_was: () -> String?

      def namespace_previously_changed?: () -> bool

      def namespace_previous_change: () -> Array[String?]?

      def namespace_previously_was: () -> String?

      def namespace_before_last_save: () -> String?

      def namespace_change_to_be_saved: () -> Array[String?]?

      def namespace_in_database: () -> String?

      def saved_change_to_namespace: () -> Array[String?]?

      def saved_change_to_namespace?: () -> bool

      def will_save_change_to_namespace?: () -> bool

      def restore_namespace!: () -> void

      def clear_namespace_change: () -> void

      def body: () -> String?

      def body=: (String?) -> String?

      def body?: () -> bool

      def body_changed?: () -> bool

      def body_change: () -> [ String?, String? ]

      def body_will_change!: () -> void

      def body_was: () -> String?

      def body_previously_changed?: () -> bool

      def body_previous_change: () -> Array[String?]?

      def body_previously_was: () -> String?

      def body_before_last_save: () -> String?

      def body_change_to_be_saved: () -> Array[String?]?

      def body_in_database: () -> String?

      def saved_change_to_body: () -> Array[String?]?

      def saved_change_to_body?: () -> bool

      def will_save_change_to_body?: () -> bool

      def restore_body!: () -> void

      def clear_body_change: () -> void

      def resource_type: () -> String?

      def resource_type=: (String?) -> String?

      def resource_type?: () -> bool

      def resource_type_changed?: () -> bool

      def resource_type_change: () -> [ String?, String? ]

      def resource_type_will_change!: () -> void

      def resource_type_was: () -> String?

      def resource_type_previously_changed?: () -> bool

      def resource_type_previous_change: () -> Array[String?]?

      def resource_type_previously_was: () -> String?

      def resource_type_before_last_save: () -> String?

      def resource_type_change_to_be_saved: () -> Array[String?]?

      def resource_type_in_database: () -> String?

      def saved_change_to_resource_type: () -> Array[String?]?

      def saved_change_to_resource_type?: () -> bool

      def will_save_change_to_resource_type?: () -> bool

      def restore_resource_type!: () -> void

      def clear_resource_type_change: () -> void

      def resource_id: () -> Integer?

      def resource_id=: (Integer?) -> Integer?

      def resource_id?: () -> bool

      def resource_id_changed?: () -> bool

      def resource_id_change: () -> [ Integer?, Integer? ]

      def resource_id_will_change!: () -> void

      def resource_id_was: () -> Integer?

      def resource_id_previously_changed?: () -> bool

      def resource_id_previous_change: () -> Array[Integer?]?

      def resource_id_previously_was: () -> Integer?

      def resource_id_before_last_save: () -> Integer?

      def resource_id_change_to_be_saved: () -> Array[Integer?]?

      def resource_id_in_database: () -> Integer?

      def saved_change_to_resource_id: () -> Array[Integer?]?

      def saved_change_to_resource_id?: () -> bool

      def will_save_change_to_resource_id?: () -> bool

      def restore_resource_id!: () -> void

      def clear_resource_id_change: () -> void

      def author_type: () -> String?

      def author_type=: (String?) -> String?

      def author_type?: () -> bool

      def author_type_changed?: () -> bool

      def author_type_change: () -> [ String?, String? ]

      def author_type_will_change!: () -> void

      def author_type_was: () -> String?

      def author_type_previously_changed?: () -> bool

      def author_type_previous_change: () -> Array[String?]?

      def author_type_previously_was: () -> String?

      def author_type_before_last_save: () -> String?

      def author_type_change_to_be_saved: () -> Array[String?]?

      def author_type_in_database: () -> String?

      def saved_change_to_author_type: () -> Array[String?]?

      def saved_change_to_author_type?: () -> bool

      def will_save_change_to_author_type?: () -> bool

      def restore_author_type!: () -> void

      def clear_author_type_change: () -> void

      def author_id: () -> Integer?

      def author_id=: (Integer?) -> Integer?

      def author_id?: () -> bool

      def author_id_changed?: () -> bool

      def author_id_change: () -> [ Integer?, Integer? ]

      def author_id_will_change!: () -> void

      def author_id_was: () -> Integer?

      def author_id_previously_changed?: () -> bool

      def author_id_previous_change: () -> Array[Integer?]?

      def author_id_previously_was: () -> Integer?

      def author_id_before_last_save: () -> Integer?

      def author_id_change_to_be_saved: () -> Array[Integer?]?

      def author_id_in_database: () -> Integer?

      def saved_change_to_author_id: () -> Array[Integer?]?

      def saved_change_to_author_id?: () -> bool

      def will_save_change_to_author_id?: () -> bool

      def restore_author_id!: () -> void

      def clear_author_id_change: () -> void

      def created_at: () -> ActiveSupport::TimeWithZone

      def created_at=: (ActiveSupport::TimeWithZone) -> ActiveSupport::TimeWithZone

      def created_at?: () -> bool

      def created_at_changed?: () -> bool

      def created_at_change: () -> [ ActiveSupport::TimeWithZone?, ActiveSupport::TimeWithZone? ]

      def created_at_will_change!: () -> void

      def created_at_was: () -> ActiveSupport::TimeWithZone?

      def created_at_previously_changed?: () -> bool

      def created_at_previous_change: () -> Array[ActiveSupport::TimeWithZone?]?

      def created_at_previously_was: () -> ActiveSupport::TimeWithZone?

      def created_at_before_last_save: () -> ActiveSupport::TimeWithZone?

      def created_at_change_to_be_saved: () -> Array[ActiveSupport::TimeWithZone?]?

      def created_at_in_database: () -> ActiveSupport::TimeWithZone?

      def saved_change_to_created_at: () -> Array[ActiveSupport::TimeWithZone?]?

      def saved_change_to_created_at?: () -> bool

      def will_save_change_to_created_at?: () -> bool

      def restore_created_at!: () -> void

      def clear_created_at_change: () -> void

      def updated_at: () -> ActiveSupport::TimeWithZone

      def updated_at=: (ActiveSupport::TimeWithZone) -> ActiveSupport::TimeWithZone

      def updated_at?: () -> bool

      def updated_at_changed?: () -> bool

      def updated_at_change: () -> [ ActiveSupport::TimeWithZone?, ActiveSupport::TimeWithZone? ]

      def updated_at_will_change!: () -> void

      def updated_at_was: () -> ActiveSupport::TimeWithZone?

      def updated_at_previously_changed?: () -> bool

      def updated_at_previous_change: () -> Array[ActiveSupport::TimeWithZone?]?

      def updated_at_previously_was: () -> ActiveSupport::TimeWithZone?

      def updated_at_before_last_save: () -> ActiveSupport::TimeWithZone?

      def updated_at_change_to_be_saved: () -> Array[ActiveSupport::TimeWithZone?]?

      def updated_at_in_database: () -> ActiveSupport::TimeWithZone?

      def saved_change_to_updated_at: () -> Array[ActiveSupport::TimeWithZone?]?

      def saved_change_to_updated_at?: () -> bool

      def will_save_change_to_updated_at?: () -> bool

      def restore_updated_at!: () -> void

      def clear_updated_at_change: () -> void
    end
    include GeneratedAttributeMethods

    def resource: () -> untyped?
    def resource=: (untyped?) -> untyped?
    def reload_resource: () -> untyped?
    def author: () -> untyped
    def author=: (untyped?) -> untyped?
    def reload_author: () -> untyped?

    module GeneratedRelationMethods
    end

    class ActiveRecord_Relation < ::ActiveRecord::Relation
      include GeneratedRelationMethods
      include _ActiveRecord_Relation[ActiveAdmin::Comment, Integer]
      include Enumerable[ActiveAdmin::Comment]
    end

    class ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
      include GeneratedRelationMethods
      include _ActiveRecord_Relation[ActiveAdmin::Comment, Integer]
    end
  end
end
