name: Ruby on Rails CI

on:
  push:
    branches:
      - dev

jobs:
  build_test_and_merge_to_master:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: recario
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:6
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.0'
          bundler-cache: true

      - name: Install Postgres dependencies
        run: sudo apt-get install postgresql-client -y

      - name: Install Redis dependencies
        run: sudo apt-get install redis -y

      - name: Bundle Install
        run: bundle install --jobs 4 --retry 3

      - name: Install RBS collection
        run: bundle exec rbs collection install

      - name: Run StandardRB
        run: bin/standardrb --fix

      - name: Run Steep check
        run: bundle exec steep check

      - name: Run RSpec
        env:
          RAILS_ENV: test
          POSTGRES_PASSWORD: postgres
          DO_SPACE_KEY: secret
          DO_SPACE_SECRET: secret
          DO_SPACE_NAME: fake
          DO_SPACE_REGION: fake
          RSPEC_RETRY_LIMIT: 3
        run: bin/rails db:migrate && bin/rspec

      - name: Merge to master
        uses: octokit/request-action@v2.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          route: POST /repos/${{ github.repository }}/merges
          mediaType: '{"Accept": "application/vnd.github.v3+json", "Authorization": "Bearer ${{ secrets.GITHUB_TOKEN }}"}'
          data: '{"head": "${{ github.ref }}", "base": "master"}'